config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/hotels' => 'hotels#index'
  get '/hotels/:id' => 'hotels#show', :as => :hotel

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :rooms
  validates :name, presence: true

  def to_s
    return self.name
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
# index action that delivers a list of hotels
  def index # in rails instance methods in controllers
            # are called actions
    @hotels = Hotel.all

  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def to_s
    return self.name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/index.html.erb
<h1>Hotels</h1>
<% @hotels.each do |hotel| %>
<div><%= link_to "#{hotel} (#{hotel.location})", hotel_path(hotel) %> </div>
<% end %>

app/views/hotels/show.html.erb
<%= link_to "hotels", hotels_path %>
<h1><%= @hotel %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>